name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  preflight:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - run: echo "✅ Preflight OK — starting build"

  build:
    needs: preflight
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Check for Node project
        run: |
          if [ -f package.json ]; then
            echo "Node project detected"
          else
            echo "No Node project — skipping npm steps"
          fi

      - name: Install deps (if Node project)
        if: exists('package.json')
        run: npm install

      - name: Build (if Node project)
        if: exists('package.json')
        run: npm run build --if-present

      - name: Tests (if Node project)
        if: exists('package.json')
        run: npm test --if-present
