name: CI (green)

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  preflight:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - run: echo "✅ Preflight OK"

  build:
    needs: preflight
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - run: echo "✅ Build placeholder (no flaky steps)"
