name: CI
on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  preflight:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - run: echo "Preflight OK — starting build…"

  build:
    needs: preflight
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install deps
        run: |
          if [ -f package.json ]; then npm ci || npm install; else echo "No Node project"; fi
      - name: Build
        run: |
          if [ -f package.json ]; then npm run build --if-present; else echo "Skip build"; fi
      - name: Tests
        run: |
          if [ -f package.json ]; then npm test --if-present; else echo "No tests"; fi
