name: Deploy to Firebase

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
        cache-dependency-path: './verum-omnis-founders-gift-v5/verum-omnis-monorepo/functions/package-lock.json'
    
    - name: Set up Java 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    
    - name: Install Functions dependencies
      working-directory: ./verum-omnis-founders-gift-v5/verum-omnis-monorepo/functions
      run: npm ci
    
    - name: Test Functions (verify immutable pack)
      working-directory: ./verum-omnis-founders-gift-v5/verum-omnis-monorepo/functions
      run: node -e "import('./index.js').then(() => console.log('Immutable pack verification passed'))"
    
    - name: Install Capacitor dependencies
      working-directory: ./verum-omnis-founders-gift-v5/verum-omnis-monorepo/capacitor-app
      run: npm ci
    
    - name: Build web assets for mobile
      working-directory: ./verum-omnis-founders-gift-v5/verum-omnis-monorepo/capacitor-app
      run: npm run build
    
    - name: Run Android unit tests
      working-directory: ./verum-omnis-founders-gift-v5/verum-omnis-monorepo/capacitor-app/android
      run: ./gradlew :app:test --no-build-cache --warning-mode all

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
        cache-dependency-path: './verum-omnis-founders-gift-v5/verum-omnis-monorepo/functions/package-lock.json'
    
    - name: Install Firebase CLI
      run: npm install -g firebase-tools
    
    - name: Install Functions dependencies
      working-directory: ./verum-omnis-founders-gift-v5/verum-omnis-monorepo/functions
      run: npm ci
    
    - name: Deploy to Firebase
      working-directory: ./verum-omnis-founders-gift-v5/verum-omnis-monorepo
      run: firebase deploy --only hosting,functions --project gitverum
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}