name: Firebase Deploy (Hosting + Functions)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

env:
  # CHANGE THIS ONLY IF YOUR MONOREPO PATHS DIFFER
  MONO_ROOT: verum-omnis-founders-gift-v5/verum-omnis-monorepo
  WEB_DIR: verum-omnis-founders-gift-v5/verum-omnis-monorepo/web
  FUNCTIONS_DIR: verum-omnis-founders-gift-v5/verum-omnis-monorepo/functions

  # Required: GitHub → Settings → Secrets and variables → Actions
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

jobs:
  deploy:
    runs-on: ubuntu-24.04
    timeout-minutes: 45

    steps:
      - name: Checkout
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # --- Build web ---
      - name: Install web dependencies
        working-directory: ${{ env.WEB_DIR }}
        run: npm ci || npm install

      - name: Build web
        working-directory: ${{ env.WEB_DIR }}
        run: npm run build

      # --- Prepare Functions (optional but recommended for lockfile integrity) ---
      - name: Install functions dependencies
        working-directory: ${{ env.FUNCTIONS_DIR }}
        run: npm ci || npm install

      # --- Auth for Firebase CLI using Service Account JSON ---
      - name: Write service account key
        run: |
          echo "${FIREBASE_SERVICE_ACCOUNT}" > "${GITHUB_WORKSPACE}/gcp-key.json"
          # Basic sanity check
          jq -r '.project_id' "${GITHUB_WORKSPACE}/gcp-key.json"
      - name: Install Firebase CLI
        run: npm i -g firebase-tools

      # If PROJECT_ID is not set as a secret, try to read from the key file
      - name: Resolve PROJECT_ID fallback
        id: proj
        run: |
          if [ -z "${PROJECT_ID}" ] || [ "${PROJECT_ID}" = "null" ]; then
            export PROJECT_ID="$(jq -r '.project_id' "${GITHUB_WORKSPACE}/gcp-key.json")"
            echo "PROJECT_ID=${PROJECT_ID}" >> $GITHUB_ENV
          fi
          echo "Resolved PROJECT_ID=${PROJECT_ID:-$PROJECT_ID}"

      # --- Deploy from the monorepo root where firebase.json lives ---
      - name: Deploy Hosting + Functions
        working-directory: ${{ env.MONO_ROOT }}
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp-key.json
        run: |
          firebase --project "${PROJECT_ID}" deploy --only hosting,functions
